/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLTV.GUI;

import QLTV.DAO.DangNhap_DAO;
import QLTV.DAO.DocGia_DAO;
import QLTV.DAO.PhieuMuon_DAO;
import QLTV.DAO.TaiLieu_DAO;
import QLTV.POJO.ChiTietPhieuMuon;
import QLTV.POJO.PhieuMuon;
import java.awt.Color;
import java.awt.Graphics;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Hashtable;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Administrator
 */
public class QL_MuonTaiLieu extends javax.swing.JInternalFrame {

    DefaultTableModel dtm = new DefaultTableModel();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    Calendar hanTra = Calendar.getInstance();
    boolean check = false, flag = false, checkInsert = false;
    String maNV, maPhieu;
    List<String> ds_MaDG = null, ds_MaTL = null;
    ChiTietPhieuMuon ctpm = new ChiTietPhieuMuon();
    /**
     * Creates new form QL_MuonTaiLieu
     */
    public QL_MuonTaiLieu() {
        initComponents();
        maNV = DangNhap_DAO.layMaNhanVien();
        dtm.addColumn("Mã Phiếu mượn");
        dtm.addColumn("Mã Chi Tiết");
        dtm.addColumn("Mã Nhân viên");
        dtm.addColumn("Mã Đọc giả");
        dtm.addColumn("Trạng thái");
        dtm.addColumn("Ngày lập phiếu");
        loadCombobox();
        setEnable_False();
        hienThiDanhSach();
        tblDSPhieuMuon.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMaPhieuMuon = new javax.swing.JTextField();
        txtTenDG = new javax.swing.JTextField();
        txtNgayMuon = new javax.swing.JTextField();
        txtTenTL = new javax.swing.JTextField();
        txtSLMuon = new javax.swing.JTextField();
        txtHanTra = new javax.swing.JTextField();
        cboMaDG = new javax.swing.JComboBox<>();
        cboMaTL = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btnXuat = new javax.swing.JButton();
        btnTKiem = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSPhieuMuon = new javax.swing.JTable();
        nen = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(865, 555));
        setMinimumSize(new java.awt.Dimension(865, 555));
        setPreferredSize(new java.awt.Dimension(865, 555));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chi tiết Phiếu Mượn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 153, 0))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Mã phiếu mượn:");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Mã đọc giả:");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Tên đọc giả:");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Ngày mượn:");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Hạn trả:");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setText("Số lượng mượn:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 102));
        jLabel8.setText("Mã tài liệu:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 102));
        jLabel9.setText("Tên tài liệu:");

        txtMaPhieuMuon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaPhieuMuon.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMaPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaPhieuMuonActionPerformed(evt);
            }
        });

        txtTenDG.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTenDG.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTenDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDGActionPerformed(evt);
            }
        });

        txtNgayMuon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNgayMuon.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNgayMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayMuonActionPerformed(evt);
            }
        });

        txtTenTL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenTL.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTenTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenTLActionPerformed(evt);
            }
        });

        txtSLMuon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSLMuon.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSLMuon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSLMuonFocusLost(evt);
            }
        });
        txtSLMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSLMuonActionPerformed(evt);
            }
        });

        txtHanTra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtHanTra.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtHanTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHanTraActionPerformed(evt);
            }
        });

        cboMaDG.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMaDGItemStateChanged(evt);
            }
        });

        cboMaTL.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMaTLItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addComponent(jLabel5))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaPhieuMuon, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(txtTenDG, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(txtNgayMuon, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(cboMaDG, 0, 170, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboMaTL, 0, 170, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTenTL, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHanTra, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSLMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(cboMaTL, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel9)
                        .addComponent(cboMaDG, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtTenDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSLMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtHanTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 790, 190));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 204));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 102));
        jLabel11.setText("QUẢN LÍ MƯỢN TÀI LIỆU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(268, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(216, 216, 216))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 790, 40));

        btnThem.setBackground(new java.awt.Color(255, 204, 51));
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThem.setForeground(new java.awt.Color(102, 0, 102));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 90, -1));

        btnXoa.setBackground(new java.awt.Color(255, 204, 51));
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(102, 0, 102));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 90, -1));

        btnSua.setBackground(new java.awt.Color(255, 204, 51));
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSua.setForeground(new java.awt.Color(102, 0, 102));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 90, -1));

        btnMoi.setBackground(new java.awt.Color(255, 204, 51));
        btnMoi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMoi.setForeground(new java.awt.Color(102, 0, 102));
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });
        getContentPane().add(btnMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 90, -1));

        btnXuat.setBackground(new java.awt.Color(255, 204, 51));
        btnXuat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXuat.setForeground(new java.awt.Color(102, 0, 102));
        btnXuat.setText("Xuất");
        btnXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatActionPerformed(evt);
            }
        });
        getContentPane().add(btnXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 90, -1));

        btnTKiem.setBackground(new java.awt.Color(255, 204, 51));
        btnTKiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTKiem.setForeground(new java.awt.Color(102, 0, 102));
        btnTKiem.setText("Tìm kiếm");
        btnTKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKiemActionPerformed(evt);
            }
        });
        getContentPane().add(btnTKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 170, -1));

        txtTimKiem.setBackground(new java.awt.Color(204, 255, 204));
        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        getContentPane().add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 460, -1));

        tblDSPhieuMuon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblDSPhieuMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Ca trực", "Tên đăng nhập", "Đăng nhập gần nhất", "Loại nhân viên"
            }
        ));
        tblDSPhieuMuon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblDSPhieuMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSPhieuMuonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSPhieuMuon);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 790, 180));

        nen.setBackground(java.awt.Color.pink);
        nen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nen.png"))); // NOI18N
        nen.setMaximumSize(new java.awt.Dimension(735, 555));
        nen.setMinimumSize(new java.awt.Dimension(735, 555));
        getContentPane().add(nen, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 870, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaPhieuMuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaPhieuMuonActionPerformed

    private void txtTenDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDGActionPerformed

    private void txtNgayMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayMuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayMuonActionPerformed

    private void txtTenTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenTLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenTLActionPerformed

    private void txtSLMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSLMuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSLMuonActionPerformed

    private void txtHanTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHanTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHanTraActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if(txtSLMuon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Số lượng mượn !!!");
            txtSLMuon.requestFocus();
            return;
        }
        
        if(!flag) {
            //ChiTietPhieuMuon ctpm = new ChiTietPhieuMuon();
            ctpm.setMaPhieuMuon(txtMaPhieuMuon.getText());
            ctpm.setMaPhieu(maPhieu);
            ctpm.setMaDocGia(String.valueOf(cboMaDG.getSelectedItem()));
            ctpm.setTenDocGia(txtTenDG.getText());
            ctpm.setMaTaiLieu(String.valueOf(cboMaTL.getSelectedItem()));
            ctpm.setTenTaiLieu(txtTenTL.getText());
            try {
                ctpm.setSoLuongMuon(Integer.valueOf(txtSLMuon.getText()));
            } catch (NumberFormatException e) {
                txtSLMuon.requestFocus();
                return;
            }
            Date NgayMuon = Date.valueOf(txtNgayMuon.getText());
            ctpm.setNgayMuon(NgayMuon);
            Date HanTra = Date.valueOf(txtHanTra.getText());
            ctpm.setHanTra(HanTra);

            maNV = DangNhap_DAO.layMaNhanVien();
            boolean kq = PhieuMuon_DAO.themPhieuMuon(ctpm, maNV, checkInsert);
            if (kq == true) {
                JOptionPane.showMessageDialog(this, "Thêm Phiếu mượn Thành công !!");
                hienThiDanhSach();
                int insert = JOptionPane.showConfirmDialog(null, "Mượn thêm Tài liệu khác?", "Thông báo",JOptionPane.YES_NO_CANCEL_OPTION);
                if (insert == 0) {
                    String str = "CT", strMa = "";
                    int sl = tblDSPhieuMuon.getRowCount() - 1;
                    strMa = (String) String.valueOf(tblDSPhieuMuon.getValueAt(sl, 1));
                    strMa = strMa.substring(2, 4);
                    int num = Integer. parseInt(strMa) + 1;
                    if (num < 10)
                       str = "CT0" + num;
                    else str = "CT" + num;
                    maPhieu = str;
                    txtSLMuon.setText("");
                    cboMaDG.setEnabled(false);
                    cboMaTL.requestFocus();
                    checkInsert = true;
                }
                else setEnable_False();
            }
            else JOptionPane.showMessageDialog(this, "Thêm Phiếu mượn Thất Bại");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (txtMaPhieuMuon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Phiếu mượn !!!");
            return;
        }
        int delete = JOptionPane.showConfirmDialog(null, "Chắc chắn muốn Xóa Phiếu mượn có mã: "+txtMaPhieuMuon.getText()+" ?", "Thông báo",JOptionPane.YES_NO_CANCEL_OPTION);
        if (delete == 0) {
            boolean kq = PhieuMuon_DAO.xoaPhieuMuon(txtMaPhieuMuon.getText());
            if (kq == true) {
                JOptionPane.showMessageDialog(this, "Xóa Phiếu mượn Thành công !!");
                setEnable_False();
                hienThiDanhSach();
            }
            else JOptionPane.showMessageDialog(this, "Xóa Phiếu mượn Thất Bại");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (txtMaPhieuMuon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Phiếu mượn !!!");
            return;
        }
        if (check) {
            //ChiTietPhieuMuon ctpm = new ChiTietPhieuMuon();
            ctpm.setMaPhieuMuon(txtMaPhieuMuon.getText());
            ctpm.setMaPhieu(maPhieu);
            ctpm.setMaDocGia(String.valueOf(cboMaDG.getSelectedItem()));
            ctpm.setTenDocGia(txtTenDG.getText());
            ctpm.setMaTaiLieu(String.valueOf(cboMaTL.getSelectedItem()));
            ctpm.setTenTaiLieu(txtTenTL.getText());
            try {
                ctpm.setSoLuongMuon(Integer.valueOf(txtSLMuon.getText()));
            } catch (NumberFormatException e) {
                txtSLMuon.requestFocus();
                return;
            }
            Date NgayMuon = Date.valueOf(txtNgayMuon.getText());
            ctpm.setNgayMuon(NgayMuon);
            Date HanTra = Date.valueOf(txtHanTra.getText());
            ctpm.setHanTra(HanTra);
        
            maNV = DangNhap_DAO.layMaNhanVien();
            boolean kq = PhieuMuon_DAO.suaPhieuMuon(ctpm, maNV);
            if (kq == true) {
                JOptionPane.showMessageDialog(this, "Cập nhật Phiếu mượn có mã: " + txtMaPhieuMuon.getText() + " thành công!!!");
                setEnable_False();
                hienThiDanhSach();
            }
            else JOptionPane.showMessageDialog(this, "Cập nhật Phiếu mượn Thất Bại");
            btnSua.setText("Sửa");
            check = false;
        } else if(!flag) {
            int update = JOptionPane.showConfirmDialog(null, "Chỉnh sửa Phiếu mượn có mã: "+txtMaPhieuMuon.getText()+" ?", "Thông báo",JOptionPane.YES_NO_CANCEL_OPTION);
            if (update == 0) {
                check = true;
                setEnable_True();
                btnSua.setText("Lưu");
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        setEnable_True();
        String strP = "PM", strMaP = "", strM = "CT", strMa = "";
        int sl = tblDSPhieuMuon.getRowCount() - 1;
        strMaP = (String) String.valueOf(tblDSPhieuMuon.getValueAt(sl, 0));
        strMaP = strMaP.substring(2, 4);
        strMa = (String) String.valueOf(tblDSPhieuMuon.getValueAt(sl, 1));
        strMa = strMa.substring(2, 4);
        int numP = Integer. parseInt(strMaP) + 1;
        if (numP < 10)
           strP = "PM0" + numP;
        else strP = "PM" + numP;
        int num = Integer. parseInt(strMa) + 1;
        if (num < 10)
           strM = "CT0" + num;
        else strM = "CT" + num;
        txtMaPhieuMuon.setText(strP);
        maPhieu = strM;
        cboMaDG.setSelectedIndex(-1);
        txtTenDG.setText("");
        cboMaTL.setSelectedIndex(-1);
        txtTenTL.setText("");
        txtSLMuon.setText("");
        Date NgayMuon = Date.valueOf(java.time.LocalDate.now());
        txtNgayMuon.setText(String.valueOf(NgayMuon));
        hanTra.roll(Calendar.DATE, 7);  // Tăng ngày thêm 8 ngày -- Sử dụng phương thức roll()
        txtHanTra.setText(String.valueOf(dateFormat.format(hanTra.getTime())));
        cboMaDG.requestFocus();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnTKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKiemActionPerformed
       String str = txtTimKiem.getText();
       if(str.startsWith("P")) {
           hienThiDanhSachTheoMa(str, 0);
       } else if(str.startsWith("N")) {
           hienThiDanhSachTheoMa(str, 1);
       } else if(str.startsWith("D")) {
           hienThiDanhSachTheoMa(str, 2);
       } else JOptionPane.showMessageDialog(this, "Gợi ý nên tìm kiếm theo mã!\n Mã Phiếu mượn: PHXX\n Mã Nhân viên: NVXX\n Mã Đọc giả: DGXX");
    }//GEN-LAST:event_btnTKiemActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
  
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void tblDSPhieuMuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSPhieuMuonMouseClicked
        int row = this.tblDSPhieuMuon.getSelectedRow();
        String maPhieuMuon = (String) tblDSPhieuMuon.getValueAt(row, 0);
        maPhieu = (String) tblDSPhieuMuon.getValueAt(row, 1);
        ChiTietPhieuMuon chiTietPhieuMuon = PhieuMuon_DAO.layThongTinChiTietPhieuMuon(maPhieuMuon, maPhieu);
        txtMaPhieuMuon.setText(chiTietPhieuMuon.getMaPhieuMuon());
        cboMaDG.setSelectedItem(String.valueOf(chiTietPhieuMuon.getMaDocGia()));
        txtTenDG.setText(chiTietPhieuMuon.getTenDocGia());
        cboMaTL.setSelectedItem(String.valueOf(chiTietPhieuMuon.getMaTaiLieu()));
        txtTenTL.setText(chiTietPhieuMuon.getTenTaiLieu());
        txtSLMuon.setText(String.valueOf(chiTietPhieuMuon.getSoLuongMuon()));
        txtNgayMuon.setText(String.valueOf(chiTietPhieuMuon.getNgayMuon()));
        txtHanTra.setText(String.valueOf(chiTietPhieuMuon.getHanTra()));
    }//GEN-LAST:event_tblDSPhieuMuonMouseClicked

    private void txtSLMuonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSLMuonFocusLost
        int sl = -1, slConLai = -1, checkINT = 1;
        slConLai = PhieuMuon_DAO.laySoLuongConLai(String.valueOf(cboMaTL.getSelectedItem()));
        try {
            sl = Integer.valueOf(txtSLMuon.getText());
            checkINT = 0;
        } catch (Exception e) {
            checkINT = 1;
            JOptionPane.showMessageDialog(this, "Vui lòng chỉ nhập số !!!");
        }
        if(checkINT == 0) {
            if(sl > 5) {
                check = false;
                flag = true;
                JOptionPane.showMessageDialog(this, "Số lượng mượn tối đa là 5 !!!");
            } else if(sl > slConLai) {
                check = false;
                flag = true;
                JOptionPane.showMessageDialog(this, "Tài liệu chỉ còn: "+slConLai+" bản in !!!");
            } else {
                check = true;
                flag = false;
            }
        }
    }//GEN-LAST:event_txtSLMuonFocusLost

    private void btnXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatActionPerformed
        if (txtMaPhieuMuon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Phiếu mượn !!!");
            return;
        }
        xuatPhieuMuon();
    }//GEN-LAST:event_btnXuatActionPerformed

    private void cboMaDGItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMaDGItemStateChanged
        String name = DocGia_DAO.layHoTenDocGia(String.valueOf(cboMaDG.getSelectedItem()));
        txtTenDG.setText(name);
    }//GEN-LAST:event_cboMaDGItemStateChanged

    private void cboMaTLItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMaTLItemStateChanged
        String name = TaiLieu_DAO.layTenTaiLieu(String.valueOf(cboMaTL.getSelectedItem()));
        txtTenTL.setText(name);
    }//GEN-LAST:event_cboMaTLItemStateChanged

    private void xuatPhieuMuon() {
        try {
            Hashtable map = new Hashtable();
            JasperReport rpt = JasperCompileManager.compileReport("src/QLTV/REPORT/rptPhieuMuon.jrxml");
            map.put("sMaPhieuMuon", txtMaPhieuMuon.getText());
            String connectionURL = PhieuMuon_DAO.getConnectionURL();
            System.out.println(connectionURL);
            Connection conn = DriverManager.getConnection(connectionURL);
            JasperPrint p = JasperFillManager.fillReport(rpt, map, conn);
            JasperViewer.viewReport(p, false);
        } catch (Exception e) { e.printStackTrace(); }
    }
    
    private void hienThiDanhSach() {
        ArrayList<PhieuMuon> ds = PhieuMuon_DAO.layDSPhieuMuon();
        dtm.setRowCount(0);
        for(PhieuMuon pm: ds) {
            Vector<Object> v = new Vector<Object>();
            v.add(pm.getMaPhieuMuon());
            v.add(pm.getMaPhieu());
            v.add(pm.getMaNVLap());
            v.add(pm.getMaDG());
            v.add(pm.getTinhTrang());
            v.add(pm.getNgayLap());
            dtm.addRow(v);
        }
        tblDSPhieuMuon.setModel(dtm);
    }
    
    private void loadCombobox() {
        ds_MaDG = DocGia_DAO.layDSMaDocGia();
        for (String maDG : ds_MaDG) {
            cboMaDG.addItem(maDG);
        }
        cboMaDG.setSelectedIndex(-1);
        cboMaDG.setRenderer(new DefaultListCellRenderer() {
            public void paint(Graphics g) {
                setForeground(Color.BLACK);
                super.paint(g);
            }
        });
        ds_MaTL = TaiLieu_DAO.layDSMaTaiLieu();
        for (String maTL : ds_MaTL) {
            cboMaTL.addItem(maTL);
        }
        cboMaTL.setSelectedIndex(-1);
        cboMaTL.setRenderer(new DefaultListCellRenderer() {
            public void paint(Graphics g) {
                setForeground(Color.BLACK);
                super.paint(g);
            }
        });
    }
    
    private void hienThiDanhSachTheoMa(String ma, int n) {
        ArrayList<PhieuMuon> ds = PhieuMuon_DAO.layDSPhieuMuonTheoMa(ma, n);
        dtm.setRowCount(0);
        for(PhieuMuon pm: ds) {
            Vector<Object> v = new Vector<Object>();
            v.add(pm.getMaPhieuMuon());
            v.add(pm.getMaPhieu());
            v.add(pm.getMaNVLap());
            v.add(pm.getMaDG());
            v.add(pm.getTinhTrang());
            v.add(pm.getNgayLap());
            dtm.addRow(v);
        }
        tblDSPhieuMuon.setModel(dtm);
    }
    
    private void setEnable_False() {
        txtMaPhieuMuon.setEnabled(false);
        cboMaDG.setEnabled(false);
        txtTenDG.setEnabled(false);
        cboMaTL.setEnabled(false);
        txtTenTL.setEnabled(false);
        txtSLMuon.setEnabled(false);
        txtNgayMuon.setEnabled(false);
        txtHanTra.setEnabled(false);        
        btnThem.setEnabled(false);
        checkInsert = false;
    }
    
    private void setEnable_True() {
        cboMaDG.setEnabled(true);
        cboMaTL.setEnabled(true);
        txtSLMuon.setEnabled(true);       
        btnThem.setEnabled(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTKiem;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuat;
    private javax.swing.JComboBox<String> cboMaDG;
    private javax.swing.JComboBox<String> cboMaTL;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nen;
    private javax.swing.JTable tblDSPhieuMuon;
    private javax.swing.JTextField txtHanTra;
    private javax.swing.JTextField txtMaPhieuMuon;
    private javax.swing.JTextField txtNgayMuon;
    private javax.swing.JTextField txtSLMuon;
    private javax.swing.JTextField txtTenDG;
    private javax.swing.JTextField txtTenTL;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
