/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package QLTV.GUI;

import QLTV.DAO.NhanVien_DAO;
import QLTV.POJO.NhanVien;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultListCellRenderer;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class QL_NhanVien extends javax.swing.JInternalFrame {

    DefaultTableModel dtm = new DefaultTableModel();
    List<String> lst = new ArrayList<>();
    boolean check = false;
    String ImagePath = null;
    
    /**
     * Creates new form QL_NhanVienNew
     */
    public QL_NhanVien() {
        initComponents();
        tblDSNhanVien.setModel(dtm);
        dtm.addColumn("Mã Nhân viên");
        dtm.addColumn("Họ Tên");
        dtm.addColumn("Ngày Sinh");
        dtm.addColumn("Tên Đăng nhập");
        dtm.addColumn("Quyền");
        dtm.addColumn("Số Điện Thoại");
        dtm.addColumn("Image Path");
        hienThiDanhSach();
        List<String> ds_lnv = NhanVien_DAO.loadCbo_LoaiNV();
        for (String lnv : ds_lnv) {
            cboLoaiNV.addItem(lnv);
        }
        cboLoaiNV.setSelectedIndex(-1);
        cboLoaiNV.setRenderer(new DefaultListCellRenderer() {
            public void paint(Graphics g) {
                setForeground(Color.BLACK);
                super.paint(g);
            }
        });
        setEnable_False();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        btnTKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSNhanVien = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTenDN = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        cboLoaiNV = new javax.swing.JComboBox<>();
        txtMaNV = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblAnhNV = new javax.swing.JLabel();
        btnChon = new javax.swing.JButton();
        nen = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(865, 555));
        setMinimumSize(new java.awt.Dimension(865, 555));
        setPreferredSize(new java.awt.Dimension(865, 555));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnThem.setBackground(new java.awt.Color(255, 204, 51));
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThem.setForeground(new java.awt.Color(102, 0, 102));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 100, -1));

        btnXoa.setBackground(new java.awt.Color(255, 204, 51));
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(102, 0, 102));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 100, -1));

        btnSua.setBackground(new java.awt.Color(255, 204, 51));
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSua.setForeground(new java.awt.Color(102, 0, 102));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 100, -1));

        btnMoi.setBackground(new java.awt.Color(255, 204, 51));
        btnMoi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMoi.setForeground(new java.awt.Color(102, 0, 102));
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });
        getContentPane().add(btnMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 100, -1));

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        getContentPane().add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 380, 30));

        btnTKiem.setBackground(new java.awt.Color(255, 204, 51));
        btnTKiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTKiem.setForeground(new java.awt.Color(102, 0, 102));
        btnTKiem.setText("Tìm kiếm");
        btnTKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKiemActionPerformed(evt);
            }
        });
        getContentPane().add(btnTKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 180, -1));

        tblDSNhanVien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblDSNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Ca trực", "Tên đăng nhập", "Đăng nhập gần nhất", "Loại nhân viên"
            }
        ));
        tblDSNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblDSNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSNhanVien);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 810, 210));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 204));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setText("QUẢN LÍ NHÂN VIÊN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 820, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 153, 0))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Tên đăng nhập:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Số điện thoại:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("Loại nhân viên:");

        txtTenDN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenDN.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        txtSDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSDT.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        cboLoaiNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtMaNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaNV.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 102));
        jLabel10.setText("Mã nhân viên:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Họ tên:");

        txtHoTen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtHoTen.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        txtNgaySinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNgaySinh.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Ngày sinh: ");

        lblAnhNV.setBackground(new java.awt.Color(51, 51, 255));
        lblAnhNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnhNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Hopstarter-Soft-Scraps-User-Administrator-Blue.16.png"))); // NOI18N
        lblAnhNV.setLabelFor(lblAnhNV);
        lblAnhNV.setText("Ảnh nhân viên");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboLoaiNV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(lblAnhNV, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboLoaiNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblAnhNV, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 810, 150));

        btnChon.setBackground(new java.awt.Color(255, 204, 51));
        btnChon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnChon.setForeground(new java.awt.Color(102, 0, 102));
        btnChon.setText("Chọn ảnh");
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });
        getContentPane().add(btnChon, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 120, -1));

        nen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nen.png"))); // NOI18N
        getContentPane().add(nen, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 870, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String quyen = null;
        if (cboLoaiNV.getSelectedItem().equals("Quản trị")) {
            quyen = "AD";
        } else quyen = "TT";
        if(!NhanVien_DAO.checkTenDN(txtTenDN.getText())) {
            JOptionPane.showMessageDialog(this, "Đã tồn tại tài khoản: " + txtTenDN.getText() +" !!!");
            return;
        }
        if(txtHoTen.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên Nhân viên !!!");
            txtHoTen.requestFocus();
            return;
        } else if(txtTenDN.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên Đăng nhập !!!");
            txtTenDN.requestFocus();
            return;
        }
        
        NhanVien nv = new NhanVien();
        nv.setMaNV(txtMaNV.getText());
        nv.setHoTen(txtHoTen.getText());
        Date NgaySinh;
        try { 
            NgaySinh = Date.valueOf(txtNgaySinh.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Nhập sai Ngày Sinh!! Định dạng: yyyy-MM-dd");
            txtNgaySinh.setText("");
            txtNgaySinh.requestFocus();
            return;
        }
        nv.setNgaySinh(NgaySinh);
        nv.setTenDN(txtTenDN.getText());
        nv.setSdt(txtSDT.getText());
        nv.setLoaiNV(quyen);
        nv.setAnh(ImagePath);
        boolean kq = NhanVien_DAO.themNhanVien(nv);
        if (kq == true) {
            JOptionPane.showMessageDialog(this, "Thêm Nhân viên Thành công !!");
            btnChon.setEnabled(false);
            setEnable_False();
            hienThiDanhSach();
        }
        else JOptionPane.showMessageDialog(this, "Thêm Nhân viên Thất Bại");
    }//GEN-LAST:event_btnThemActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void tblDSNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSNhanVienMouseClicked
        int row = this.tblDSNhanVien.getSelectedRow();
        txtMaNV.setText((String) tblDSNhanVien.getValueAt(row, 0));
        txtHoTen.setText((String) tblDSNhanVien.getValueAt(row, 1));
        txtNgaySinh.setText((String) String.valueOf(tblDSNhanVien.getValueAt(row, 2)));
        txtTenDN.setText((String) tblDSNhanVien.getValueAt(row, 3));
        txtSDT.setText((String) String.valueOf(tblDSNhanVien.getValueAt(row, 5)));
        if (tblDSNhanVien.getValueAt(row, 4).equals("AD")) {
            cboLoaiNV.setSelectedIndex(0);
        } else cboLoaiNV.setSelectedIndex(1);
        ImagePath = (String) tblDSNhanVien.getValueAt(row, 6);
        lblAnhNV.setIcon(resizeImage(ImagePath));
    }//GEN-LAST:event_tblDSNhanVienMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (txtMaNV.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Nhân viên !!!");
            return;
        }
        NhanVien nv = new NhanVien();
        nv.setMaNV(txtMaNV.getText());
        nv.setTenDN(txtTenDN.getText());
        int delete = JOptionPane.showConfirmDialog(null, "Chắc chắn muốn Xóa Nhân viên có mã: "+txtMaNV.getText()+" ?", "Thông báo",JOptionPane.YES_NO_CANCEL_OPTION);
        if (delete == 0) {
            boolean kq = NhanVien_DAO.xoaNhanVien(nv);
            if (kq == true) {
                JOptionPane.showMessageDialog(this, "Xóa Nhân viên Thành công !!");
                setEnable_False();
                hienThiDanhSach();
            }
            else JOptionPane.showMessageDialog(this, "Xóa Nhân viên Thất Bại");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (txtMaNV.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Nhân viên !!!");
            check = false;
            return;
        }
        btnChon.setEnabled(true);
        String quyen = null;
        if (cboLoaiNV.getSelectedItem().equals("Quản trị")) {
            quyen = "AD";
        } else quyen = "TT";
        if (check) {
            NhanVien nv = new NhanVien();
            nv.setMaNV(txtMaNV.getText());
            nv.setHoTen(txtHoTen.getText());
            Date NgaySinh = null;
            try { 
                NgaySinh = Date.valueOf(txtNgaySinh.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Nhập sai Ngày Sinh!! Định dạng: yyyy-MM-dd");
                txtNgaySinh.setText("");
                txtNgaySinh.requestFocus();
                return;
            }
            nv.setNgaySinh(NgaySinh);
            nv.setTenDN(txtTenDN.getText());
            nv.setSdt(txtSDT.getText());
            nv.setLoaiNV(quyen);
            nv.setAnh(ImagePath);
            boolean kq = NhanVien_DAO.suaNhanVien(nv);
            if (kq == true) {
                JOptionPane.showMessageDialog(this, "Cập nhật Nhân viên có mã: " + txtMaNV.getText() + " thành công!!!");
                setEnable_False();
                hienThiDanhSach();
            }
            else JOptionPane.showMessageDialog(this, "Cập nhật Nhân viên Thất Bại");
            btnSua.setText("Sửa");
            check = false;
        } else {
            int update = JOptionPane.showConfirmDialog(null, "Chỉnh sửa Nhân viên có mã: "+txtMaNV.getText()+" ?", "Thông báo",JOptionPane.YES_NO_CANCEL_OPTION);
            if (update == 0) {
                check = true;
                setEnable_True();
                btnSua.setText("Lưu");
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        setEnable_True();
        cboLoaiNV.setSelectedIndex(-1);
        txtSDT.setText("");
        txtNgaySinh.setText("");
        txtHoTen.setText("");
        txtTenDN.setText("");
        
        String str = "NV", strMa = "";
        int sl = tblDSNhanVien.getRowCount() - 1;
        strMa = (String) String.valueOf(tblDSNhanVien.getValueAt(sl, 0));
        strMa = strMa.substring(2, 4);
        int num = Integer. parseInt(strMa) + 1;
        if (num < 10)
           str = "NV0" + num;
        else str = "NV" + num;
        txtMaNV.setText(str);
        btnThem.setEnabled(true);
        btnChon.setEnabled(true);
        cboLoaiNV.setSelectedIndex(0);
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnTKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKiemActionPerformed
        String str = txtTimKiem.getText();
        ArrayList<NhanVien> ds = NhanVien_DAO.layDSNhanVienTheoYC(str);
        dtm.setRowCount(0);
        for (NhanVien nv: ds) {
            Vector<Object> v = new Vector<Object>();
            v.add(nv.getMaNV());
            v.add(nv.getHoTen());
            v.add(nv.getNgaySinh());
            v.add(nv.getTenDN());
            v.add(nv.getLoaiNV());
            v.add(nv.getSdt());
            v.add(nv.getAnh());
            dtm.addRow(v);
        }
        tblDSNhanVien.setModel(dtm);
    }//GEN-LAST:event_btnTKiemActionPerformed

    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
        try {
            JFileChooser chooser = new JFileChooser("..\\QuanLyThuVien_Nhom8\\src\\img");
            chooser.setDialogTitle("Mở File");
            chooser.showOpenDialog(null);
            File file = chooser.getSelectedFile();
            ImagePath = file.getAbsolutePath().replace("//","--");
        if(ImagePath != null)
            lblAnhNV.setIcon(frameIcon);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn Ảnh");
        }
    }//GEN-LAST:event_btnChonActionPerformed

    private void setEnable_False() {
        txtMaNV.setEnabled(false);
        txtNgaySinh.setEnabled(false);
        txtSDT.setEnabled(false);
        txtTenDN.setEnabled(false);
        txtHoTen.setEnabled(false);
        cboLoaiNV.setEnabled(false);
        btnThem.setEnabled(false);
        btnChon.setEnabled(false);
    }
    
    private void setEnable_True() {
        txtNgaySinh.setEnabled(true);
        txtSDT.setEnabled(true);
        txtTenDN.setEnabled(true);
        txtHoTen.setEnabled(true);
        cboLoaiNV.setEnabled(true);
    }
    
    private void hienThiDanhSach() {
        ArrayList<NhanVien> ds = NhanVien_DAO.layDSNhanVien();
        dtm.setRowCount(0);
        for (NhanVien nv: ds) {
            Vector<Object> v = new Vector<Object>();
            v.add(nv.getMaNV());
            v.add(nv.getHoTen());
            v.add(nv.getNgaySinh());
            v.add(nv.getTenDN());
            v.add(nv.getLoaiNV());
            v.add(nv.getSdt());
            v.add(nv.getAnh());
            dtm.addRow(v);
        }
        tblDSNhanVien.setModel(dtm);
    }
    
    public ImageIcon resizeImage(String ImagePath) {
        ImageIcon icon = new ImageIcon(ImagePath);
        Image img = icon.getImage();
        //Image newImg = img.getScaledInstance(lblAnhNV.getWidth(), lblAnhNV.getHeight(), Image.SCALE_SMOOTH);
        Image newImg = img.getScaledInstance(102, 118, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChon;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTKiem;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboLoaiNV;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnhNV;
    private javax.swing.JLabel nen;
    private javax.swing.JTable tblDSNhanVien;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenDN;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
