/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package QLTV.GUI;

import QLTV.DAO.TaiLieu_DAO;
import QLTV.POJO.TaiLieu;
import java.awt.Image;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class QL_TaiLieu extends javax.swing.JInternalFrame {

    DefaultTableModel dtm = new DefaultTableModel();
    boolean check = false, checkBtnMoi = false, checkx= false;
    String ImagePath = null;
    /**
     * Creates new form QL_SachNew
     */
    public QL_TaiLieu() {
        initComponents();
        dtm.addColumn("Mã Tài liệu");
        dtm.addColumn("Tên Tài liệu");
        dtm.addColumn("Tác giả");
        dtm.addColumn("Tổng số");
        dtm.addColumn("Còn lại");
        dtm.addColumn("Giá");
        dtm.addColumn("Image Path");
        setEnable_False();
        hienThiDanhSach();
        tblDSTaiLieu.setModel(dtm);
        btnThem.setEnabled(true);
        btnThem.setText("Nhập");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        btnTKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSTaiLieu = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaTaiLieu = new javax.swing.JTextField();
        txtTenTaiLieu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTacGia = new javax.swing.JTextField();
        txtTongSo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtConLai = new javax.swing.JTextField();
        txtGiaBan = new javax.swing.JTextField();
        lblAnhNV = new javax.swing.JLabel();
        btnChon = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(865, 555));
        setMinimumSize(new java.awt.Dimension(865, 555));
        setPreferredSize(new java.awt.Dimension(865, 555));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 204));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 102));
        jLabel11.setText("QUẢN LÍ TÀI LIỆU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(328, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(302, 302, 302))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 850, 40));

        btnThem.setBackground(new java.awt.Color(255, 204, 51));
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThem.setForeground(new java.awt.Color(102, 0, 102));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 100, 30));

        btnXoa.setBackground(new java.awt.Color(255, 204, 51));
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(102, 0, 102));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 100, -1));

        btnSua.setBackground(new java.awt.Color(255, 204, 51));
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSua.setForeground(new java.awt.Color(102, 0, 102));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 100, 30));

        btnMoi.setBackground(new java.awt.Color(255, 204, 51));
        btnMoi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMoi.setForeground(new java.awt.Color(102, 0, 102));
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });
        getContentPane().add(btnMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 100, 30));

        btnPrint.setBackground(new java.awt.Color(255, 204, 51));
        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(102, 0, 102));
        btnPrint.setText("Print");
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 210, 130, 30));

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 380, -1));

        btnTKiem.setBackground(new java.awt.Color(255, 204, 51));
        btnTKiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTKiem.setForeground(new java.awt.Color(102, 0, 102));
        btnTKiem.setText("Tìm kiếm");
        btnTKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKiemActionPerformed(evt);
            }
        });
        getContentPane().add(btnTKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 160, -1));

        tblDSTaiLieu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblDSTaiLieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Hiện trạng", "Loại sách"
            }
        ));
        tblDSTaiLieu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblDSTaiLieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSTaiLieuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSTaiLieu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 790, 190));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin tài liệu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 153, 0))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Mã tài liệu:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Tên tài liệu:");

        txtMaTaiLieu.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtMaTaiLieu.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMaTaiLieu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaTaiLieuFocusLost(evt);
            }
        });
        txtMaTaiLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaTaiLieuActionPerformed(evt);
            }
        });

        txtTenTaiLieu.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtTenTaiLieu.setToolTipText("");
        txtTenTaiLieu.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTenTaiLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenTaiLieuActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Số lượng:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Còn lại:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("Tác giả:");

        txtTacGia.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtTacGia.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTacGiaActionPerformed(evt);
            }
        });

        txtTongSo.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtTongSo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTongSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongSoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setText("Giá bán:");

        txtConLai.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtConLai.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtConLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConLaiActionPerformed(evt);
            }
        });

        txtGiaBan.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtGiaBan.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtGiaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaBanActionPerformed(evt);
            }
        });

        lblAnhNV.setBackground(new java.awt.Color(51, 51, 255));
        lblAnhNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnhNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Hopstarter-Soft-Scraps-User-Administrator-Blue.16.png"))); // NOI18N
        lblAnhNV.setText("Ảnh Tài liệu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(44, 44, 44)
                        .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtConLai, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTongSo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblAnhNV, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtTongSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtTenTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConLai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(23, 23, 23))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblAnhNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 790, 160));

        btnChon.setBackground(new java.awt.Color(255, 204, 51));
        btnChon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnChon.setForeground(new java.awt.Color(102, 0, 102));
        btnChon.setText("Chọn ảnh");
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });
        getContentPane().add(btnChon, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 120, -1));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nen.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 870, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaTaiLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaTaiLieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaTaiLieuActionPerformed

    private void txtTenTaiLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenTaiLieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenTaiLieuActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (txtTenTaiLieu.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Tên Tài liệu !!!");
            txtTenTaiLieu.requestFocus();
            return;
        } else if (txtTacGia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Tác giả !!!");
            txtTacGia.requestFocus();
            return;
        }
        
        TaiLieu tl = new TaiLieu();
        tl.setMaTaiLieu(txtMaTaiLieu.getText());
        tl.setSoLuong(Integer.valueOf(txtTongSo.getText()));
        tl.setTenTaiLieu(txtTenTaiLieu.getText());
        tl.setTacGia(txtTacGia.getText());
        tl.setGiaBan(Integer.valueOf(txtGiaBan.getText()));
        tl.setConLai(Integer.valueOf(txtConLai.getText()));
        
        if(checkBtnMoi) {
            boolean kq = TaiLieu_DAO.themTaiLieu(tl);
            if (kq == true) {
                JOptionPane.showMessageDialog(this, "Thêm Tài liệu Thành công !!");
                setEnable_False();
                hienThiDanhSach();
            }
            else JOptionPane.showMessageDialog(this, "Thêm Tài liệu Thất Bại");
            btnChon.setEnabled(false);
            checkBtnMoi = false;
        }
        else {
            if(checkx) {
                int sl = Integer.valueOf(txtTongSo.getText());
                boolean kq = false;
                try {
                    kq = TaiLieu_DAO.nhapTaiLieu(tl, sl);
                } catch (SQLException ex) {
                    Logger.getLogger(QL_TaiLieu.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (kq == true) {
                    JOptionPane.showMessageDialog(this, "Nhập Tài liệu Thành công !!");
                    setEnable_False();
                    hienThiDanhSach();
                }
                else JOptionPane.showMessageDialog(this, "Nhập Tài liệu Thất Bại"); 
                
                return;
            }
            int insert = JOptionPane.showConfirmDialog(null, "Nhập thêm Tài liệu có mã: "+txtMaTaiLieu.getText()+" ?", "Thông báo",JOptionPane.YES_NO_CANCEL_OPTION);
            if (insert == 0) {
                setEnable_True();
                txtTongSo.setText("");
                checkx=true;
                txtMaTaiLieu.setEnabled(true);
                txtMaTaiLieu.requestFocus();
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnTKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKiemActionPerformed
        String str = txtTimKiem.getText();
        ArrayList<TaiLieu> ds = TaiLieu_DAO.layDSTaiLieuTheoTen(str);
        dtm.setRowCount(0);
        for(TaiLieu tl: ds) {
            Vector<Object> v = new Vector<Object>();
            v.add(tl.getMaTaiLieu());
            v.add(tl.getTenTaiLieu());
            v.add(tl.getTacGia());
            v.add(tl.getSoLuong());
            v.add(tl.getConLai());
            v.add(tl.getGiaBan());
            v.add(tl.getAnh());
            dtm.addRow(v);
        }
        tblDSTaiLieu.setModel(dtm);
    }//GEN-LAST:event_btnTKiemActionPerformed

    private void txtTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTacGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTacGiaActionPerformed

    private void txtTongSoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongSoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongSoActionPerformed

    private void txtConLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConLaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConLaiActionPerformed

    private void txtGiaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaBanActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (txtMaTaiLieu.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Tài liệu !!!");
            return;
        }
        int delete = JOptionPane.showConfirmDialog(null, "Chắc chắn muốn Xóa Tài liệu có mã: "+txtMaTaiLieu.getText()+" ?", "Thông báo",JOptionPane.YES_NO_CANCEL_OPTION);
        if (delete == 0) {
            boolean kq = TaiLieu_DAO.xoaTaiLieu(txtMaTaiLieu.getText());
            if (kq == true) {
                JOptionPane.showMessageDialog(this, "Xóa Tài liệu Thành công !!");
                setEnable_False();
                hienThiDanhSach();
            }
            else JOptionPane.showMessageDialog(this, "Xóa Tài liệu Thất Bại");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (txtMaTaiLieu.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Tài liệu !!!");
            check = false; 
            return;
        }
        btnChon.setEnabled(true);
        if (check) {
            TaiLieu tl = new TaiLieu();
            tl.setMaTaiLieu(txtMaTaiLieu.getText());
            tl.setTenTaiLieu(txtTenTaiLieu.getText());
            tl.setTacGia(txtTacGia.getText());
            tl.setSoLuong(Integer.valueOf(txtTongSo.getText()));
            tl.setConLai(Integer.valueOf(txtConLai.getText()));
            tl.setGiaBan(Integer.valueOf(txtGiaBan.getText()));
            tl.setAnh(ImagePath);
            
            boolean kq = TaiLieu_DAO.suaTaiLieu(tl);
            if (kq == true) {
                JOptionPane.showMessageDialog(this, "Cập nhật Tài liệu có mã: " + txtMaTaiLieu.getText() + " thành công!!!");
                setEnable_False();
                hienThiDanhSach();
            }
            else JOptionPane.showMessageDialog(this, "Cập nhật Tài liệu Thất Bại !");
            btnSua.setText("Sửa");
            check = false;
        } else {
            int update = JOptionPane.showConfirmDialog(null, "Chỉnh sửa Tài liệu có mã: "+txtMaTaiLieu.getText()+" ?", "Thông báo",JOptionPane.YES_NO_CANCEL_OPTION);
            if (update == 0) {
                check = true;
                setEnable_True();
                btnSua.setText("Lưu");
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        btnThem.setEnabled(true);
        btnChon.setEnabled(true);
        btnThem.setText("Thêm");
        String str = "TL", strMa = "";
        int sl = tblDSTaiLieu.getRowCount() - 1;
        strMa = (String) String.valueOf(tblDSTaiLieu.getValueAt(sl, 0));
        strMa = strMa.substring(2, 4);
        int num = Integer. parseInt(strMa) + 1;
        if (num < 10)
           str = "TL0" + num;
        else str = "TL" + num;
        txtMaTaiLieu.setText(str);
        txtTenTaiLieu.setText("");
        txtTacGia.setText("");
        txtTongSo.setText("");
        txtConLai.setText("");
        txtGiaBan.setText("");
        txtTenTaiLieu.requestFocus();
        setEnable_True();
        checkBtnMoi = true;
    }//GEN-LAST:event_btnMoiActionPerformed

    private void tblDSTaiLieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSTaiLieuMouseClicked
        int row = this.tblDSTaiLieu.getSelectedRow();
        txtMaTaiLieu.setText((String) tblDSTaiLieu.getValueAt(row, 0));
        txtTenTaiLieu.setText((String) tblDSTaiLieu.getValueAt(row, 1));
        txtTacGia.setText((String) tblDSTaiLieu.getValueAt(row, 2));
        txtTongSo.setText((String) String.valueOf(tblDSTaiLieu.getValueAt(row, 3)));
        txtConLai.setText((String) String.valueOf(tblDSTaiLieu.getValueAt(row, 4)));
        txtGiaBan.setText((String) String.valueOf(tblDSTaiLieu.getValueAt(row, 5)));
        ImagePath = (String) tblDSTaiLieu.getValueAt(row, 6);
        lblAnhNV.setIcon(resizeImage(ImagePath));
    }//GEN-LAST:event_tblDSTaiLieuMouseClicked

    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
        try {
            JFileChooser chooser = new JFileChooser("..\\QuanLyThuVien_Nhom8\\src\\img");
            chooser.setDialogTitle("Mở File");
            chooser.showOpenDialog(null);
            File file = chooser.getSelectedFile();
            ImagePath = file.getAbsolutePath().replace("//","--");
            if(ImagePath != null)
            lblAnhNV.setIcon(frameIcon);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn Ảnh");
        }
    }//GEN-LAST:event_btnChonActionPerformed

    private void txtMaTaiLieuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaTaiLieuFocusLost
        TaiLieu tl = TaiLieu_DAO.layThongTinTaiLieu(txtMaTaiLieu.getText());
        txtTenTaiLieu.setText(tl.getTenTaiLieu());
        txtGiaBan.setText(String.valueOf(tl.getGiaBan()));
        txtTacGia.setText(tl.getTacGia());
    }//GEN-LAST:event_txtMaTaiLieuFocusLost


    private void setEnable_False() {
        txtMaTaiLieu.setEnabled(false);
        txtTenTaiLieu.setEnabled(false);
        txtTacGia.setEnabled(false);
        txtTongSo.setEnabled(false);
        txtConLai.setEnabled(false);
        txtGiaBan.setEnabled(false);
        btnThem.setEnabled(false);
    }
    
    private void setEnable_True() {
        txtTenTaiLieu.setEnabled(true);
        txtTacGia.setEnabled(true);
        txtTongSo.setEnabled(true);
        txtConLai.setEnabled(true);
        txtGiaBan.setEnabled(true);
    }
    
    private void hienThiDanhSach() {
        ArrayList<TaiLieu> ds = TaiLieu_DAO.layDSTaiLieu();
        dtm.setRowCount(0);
        for(TaiLieu tl: ds) {
            Vector<Object> v = new Vector<Object>();
            v.add(tl.getMaTaiLieu());
            v.add(tl.getTenTaiLieu());
            v.add(tl.getTacGia());
            v.add(tl.getSoLuong());
            v.add(tl.getConLai());
            v.add(tl.getGiaBan());
            v.add(tl.getAnh());
            dtm.addRow(v);
        }
        tblDSTaiLieu.setModel(dtm);
    }
    
    public ImageIcon resizeImage(String ImagePath) {
        ImageIcon icon = new ImageIcon(ImagePath);
        Image img = icon.getImage();
        //Image newImg = img.getScaledInstance(lblAnhNV.getWidth(), lblAnhNV.getHeight(), Image.SCALE_SMOOTH);
        Image newImg = img.getScaledInstance(120, 140, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChon;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTKiem;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnhNV;
    private javax.swing.JTable tblDSTaiLieu;
    private javax.swing.JTextField txtConLai;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtMaTaiLieu;
    private javax.swing.JTextField txtTacGia;
    private javax.swing.JTextField txtTenTaiLieu;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTongSo;
    // End of variables declaration//GEN-END:variables
}
